#!/bin/sh

uci -q batch <<'EOF'
set network.lan.proto='static'
set network.lan.ipaddr='192.168.3.7'
set network.lan.netmask='255.255.255.0'
set network.lan.gateway='192.168.3.2'
delete network.lan.dns
add_list network.lan.dns='192.168.3.2'
delete network.lan.ip6assign

set dhcp.lan='dhcp'
set dhcp.lan.interface='lan'
set dhcp.lan.ignore='1'
set dhcp.lan.dhcpv6='disabled'
set dhcp.lan.ra='disabled'
set dhcp.lan.ndp='disabled'

set luci.main.mediaurlbase='/luci-static/bootstrap'

commit network
commit dhcp
commit luci
EOF

printf '%s\n' '123456' '123456' | passwd root >/dev/null 2>&1

exit 0
